


<div id="home-tiles" class="container-fluid metro">
    <div class="row-fluid">
        <div class="span4">
            <a class="tile wide imagetext bg-color-yellow first" href="https://github.com/carlosocarvalho">
                <div class="image-wrapper">
                    <span class="icon icon-github"/>
                </div>
                <div class="column-text">
                    <div class="text-header3">Ver o Projeto no Github</div>
                </div>
            </a>
        </div>
        <div class="span4">
            <a class="tile wide imagetext bg-color-green middle" href="./hub.html">
                <div class="image-wrapper">
                    <!--<img src="content/img/metro-tiles.jpg" alt="demo"/>-->
                    <span class="icon icon-grid-view"/>
                </div>
                <div class="column-text">
                    <div class="text-header3">View the Demo online</div>
                </div>
            </a>
        </div>
        <div class="span4">
            <a class="tile wide imagetext bg-color-blue last" href="https://twitter.com/carlosocarvalho">
                <div class="image-wrapper">
                    <span class="icon icon-twitter"/>
                </div>
                <div class="column-text">
                    <div class="text-header3">Siga-me no Twitter</div>
                </div>
            </a>
        </div>
    </div>
</div>
<div id="charms" class="win-ui-dark">
   
      <div id="theme-charms-section" class="charms-section">
         <div class="charms-header">
            <a href="#" class="close-charms win-command">
               <span class="win-commandimage win-commandring">&#xe05d;</span>
            </a>
            <h2>Settings</h2>
         </div>
   
         <div class="row-fluid">
            <div class="span12">
   
                <ul class="nav-list">
                    <li></li>
                </ul>
   
            </div>
         </div>
      </div>
   
   </div>
<?php 
add_js(array('common/home'));
?>